services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"   # Jenkins веб-интерфейс
      - "50000:50000" # Агент-соединения
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Доступ к Docker на хосте
      - jenkins_home:/var/jenkins_home # Папка Jenkins для сохранения данных
    environment:
      JENKINS_OPTS: "--httpPort=8080" # Настройка порта
    restart: always

volumes:
  jenkins_home:
    driver: local
